apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: production

images:
- name: skillc0der/memory-leaker
  newTag: 0.1.0

replicas:
- name: memory-leaker
  count: 1
