apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: preoomkiller-controller
    app.kubernetes.io/component: controller
  name: preoomkiller-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: preoomkiller-controller
      app.kubernetes.io/component: controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: preoomkiller-controller
        app.kubernetes.io/component: controller
    spec:
      affinity:
        nodeAffinity:
          required:
            nodeSelectorTerm:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
      tolerations:
      - key: CriticalAddonsOnly
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - image: skillcoder/preoomkiller-controller:latest
        imagePullPolicy: IfNotPresent
        name: preoomkiller-controller
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
            ephemeral-storage: 70Mi
          limits:
            cpu: 1050m
            memory: 50Mi
            ephemeral-storage: 70Mi
        startupProbe:
          httpGet:
            path: /-/readyz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /-/readyz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 60
          timeoutSeconds: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /-/healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 300
          timeoutSeconds: 1
          failureThreshold: 2
      restartPolicy: Always
      serviceAccountName: preoomkiller-controller
      priorityClassName: system-cluster-critical
      terminationGracePeriodSeconds: 30
