apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- ../../base

commonLabels:
  app.kubernetes.io/environment: production

images:
- name: skillcoder/preoomkiller-controller
  newTag: latest

replicas:
- name: preoomkiller-controller
  count: 1
