apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: memory-leaker
      app.kubernetes.io/part-of: memory-leaker-example
      app.kubernetes.io/managed-by: kustomize

resources:
- deployment.yaml
